version: '3.8'

services:
  telegram-whisper-bot:
    build: .
    container_name: telegram-whisper-bot
    env_file:
      - .env  # Load the token from the .env file
    restart: always
    volumes:
      - ./models:/models  # Persist Whisper models locally
      - ./logs:/app/logs  # Persistent logs for debugging
    deploy:
      resources:
        limits:
          cpus: '2.0'    # Limit to 2 CPU cores for the container
          memory: 4G     # Limit to 4 GB of RAM
    logging:
      driver: "json-file"
      options:
        max-size: "5m"  # Maximum log size per file
        max-file: "5"   # Maximum number of log files to keep
